# Generated by Django 3.2.2 on 2021-06-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='serialNo',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
