# Generated by Django 3.2.2 on 2021-06-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_auto_20210627_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='serialNo',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
