# Generated by Django 3.2.2 on 2021-06-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0003_auto_20210627_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNo', models.CharField(max_length=10000, null=True)),
                ('data', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
