# Generated by Django 3.2.2 on 2021-06-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0004_auto_20210627_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='serialNo',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
